[2023-01-04T19:56:21.793+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T19:56:15.684584+00:00 [queued]>
[2023-01-04T19:56:21.802+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T19:56:15.684584+00:00 [queued]>
[2023-01-04T19:56:21.803+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T19:56:21.804+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T19:56:21.821+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T19:56:21.871+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): augment_dataset_task> on 2023-01-04 19:56:15.684584+00:00
[2023-01-04T19:56:21.877+0000] {standard_task_runner.py:55} INFO - Started process 237 to run task
[2023-01-04T19:56:21.880+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'augment_dataset_task', 'manual__2023-01-04T19:56:15.684584+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpp4lasg7x']
[2023-01-04T19:56:21.882+0000] {standard_task_runner.py:83} INFO - Job 79: Subtask augment_dataset_task
[2023-01-04T19:56:22.213+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T19:56:15.684584+00:00 [running]> on host 4de77850e514
[2023-01-04T19:56:22.492+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=augment_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T19:56:15.684584+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T19:56:15.684584+00:00
[2023-01-04T19:56:22.496+0000] {logging_mixin.py:137} INFO - The lookup table and the augmented file already exist and are saved as csv.
[2023-01-04T19:56:22.496+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T19:56:22.508+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=augment_dataset_task, execution_date=20230104T195615, start_date=20230104T195621, end_date=20230104T195622
[2023-01-04T19:56:22.616+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T19:56:22.653+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
