[2023-01-04T20:11:11.171+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T20:11:07.718241+00:00 [queued]>
[2023-01-04T20:11:11.182+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T20:11:07.718241+00:00 [queued]>
[2023-01-04T20:11:11.182+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T20:11:11.182+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T20:11:11.183+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T20:11:11.196+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): augment_dataset_task> on 2023-01-04 20:11:07.718241+00:00
[2023-01-04T20:11:11.202+0000] {standard_task_runner.py:55} INFO - Started process 1058 to run task
[2023-01-04T20:11:11.205+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'augment_dataset_task', 'manual__2023-01-04T20:11:07.718241+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpdxmocikm']
[2023-01-04T20:11:11.207+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask augment_dataset_task
[2023-01-04T20:11:11.274+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T20:11:07.718241+00:00 [running]> on host 575b47a6f644
[2023-01-04T20:11:11.350+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=augment_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T20:11:07.718241+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T20:11:07.718241+00:00
[2023-01-04T20:11:11.353+0000] {logging_mixin.py:137} INFO - The lookup table and the augmented file already exist and are saved as csv.
[2023-01-04T20:11:11.354+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T20:11:11.367+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=augment_dataset_task, execution_date=20230104T201107, start_date=20230104T201111, end_date=20230104T201111
[2023-01-04T20:11:11.418+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T20:11:11.447+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
