[2023-01-04T20:15:46.597+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T20:14:27.377460+00:00 [queued]>
[2023-01-04T20:15:46.614+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T20:14:27.377460+00:00 [queued]>
[2023-01-04T20:15:46.614+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T20:15:46.615+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T20:15:46.620+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T20:15:46.642+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): augment_dataset_task> on 2023-01-04 20:14:27.377460+00:00
[2023-01-04T20:15:46.650+0000] {standard_task_runner.py:55} INFO - Started process 1674 to run task
[2023-01-04T20:15:46.654+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'augment_dataset_task', 'manual__2023-01-04T20:14:27.377460+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpymst0blh']
[2023-01-04T20:15:46.657+0000] {standard_task_runner.py:83} INFO - Job 102: Subtask augment_dataset_task
[2023-01-04T20:15:46.745+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.augment_dataset_task manual__2023-01-04T20:14:27.377460+00:00 [running]> on host 575b47a6f644
[2023-01-04T20:15:46.832+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=augment_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T20:14:27.377460+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T20:14:27.377460+00:00
[2023-01-04T20:15:47.016+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:4913 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T20:15:47.020+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_2.py:62 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T20:15:48.726+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:5047 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T20:16:13.857+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_2.py:75 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T20:16:17.688+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T20:16:17.698+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=augment_dataset_task, execution_date=20230104T201427, start_date=20230104T201546, end_date=20230104T201617
[2023-01-04T20:16:17.747+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T20:16:17.774+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
