[2023-01-04T16:18:34.953+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T16:16:41.990135+00:00 [queued]>
[2023-01-04T16:18:34.962+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T16:16:41.990135+00:00 [queued]>
[2023-01-04T16:18:34.963+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:18:34.963+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T16:18:34.964+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:18:34.978+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-01-04 16:16:41.990135+00:00
[2023-01-04T16:18:34.983+0000] {standard_task_runner.py:55} INFO - Started process 549 to run task
[2023-01-04T16:18:34.988+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'load_to_postgres', 'manual__2023-01-04T16:16:41.990135+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpf0_t33wb']
[2023-01-04T16:18:34.991+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask load_to_postgres
[2023-01-04T16:18:35.057+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T16:16:41.990135+00:00 [running]> on host 4de77850e514
[2023-01-04T16:18:35.131+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T16:16:41.990135+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T16:16:41.990135+00:00
[2023-01-04T16:18:36.090+0000] {logging_mixin.py:137} INFO - connected succesfully
[2023-01-04T16:18:36.110+0000] {logging_mixin.py:137} INFO - Accidents table already exists.
[2023-01-04T16:18:36.116+0000] {logging_mixin.py:137} INFO -  Look up table already exists.
[2023-01-04T16:18:36.118+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T16:18:36.128+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=load_to_postgres, execution_date=20230104T161641, start_date=20230104T161834, end_date=20230104T161836
[2023-01-04T16:18:36.164+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T16:18:36.186+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
